language: python
sudo: false
addons:
  apt:
    packages:
      - gfortran
      - libatlas-base-dev
      - libatlas-dev
python:
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "python setup.py build_ext --inplace"
# command to run tests
script: PYTHONPATH="." nosetests -w tests
