language: python
python:
  - "3.4"
  - "3.5"

cache:
  directories:
    - $HOME/miniconda3 # miniconda cache

# Setup miniconda
before_install:
  - ci/before_install_travis.sh

# command to install dependencies
install:
  - conda install -n ssvm -c sebp --file requirements.txt
  - source activate ssvm
  - python setup.py install
  - rm -fr survival

# command to run tests
script: nosetests -w tests --with-coverage --cover-package=survival --cover-tests
