name: sksurv-test
channels:
  - defaults
  - sebp
dependencies:
  - python=3.6
  - cython>=0.29
  - ecos
  - numexpr
  - numpy=1.15
  - osqp!=0.6.0,!=0.6.1
  - pytest
  - pytest-cov
  - scipy!=1.3.0
  - scikit-learn=0.22
  - pandas=0.25
