name: Tox
on: [push, pull_request]

jobs:
  linting_and_docs:
    runs-on: ubuntu-latest
    name: Linting and Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run Tox
        uses: fedora-python/tox-github-action@master
        with:
          tox_env: ${{ matrix.tox_env }}
          dnf_install: pandoc cmake make
      - name: Archive documentation
        uses: actions/upload-artifact@v1
        with:
          name: documentation
          path: doc/_build/html
        if: ${{ matrix.tox_env == 'docs' }}
    strategy:
      matrix:
        tox_env: [flake8, docs]
